### ISSUE TITLE
Handling 'out-of-vocab' words

### ISSUE THREAD

**Issue by iannho** [huseinzol05/malaya#71]
When using the method 'get_vector_by_name' on an OOV word, it returns an exception with the top-5 nearest words. Is there an instance where I can extract this top-5 nearest words returned so that I can use those word vectors?

Also, what word2vec model was used to train this? Is there a way to train the pre-trained model with new words?

**Comment by huseinzol05** [comment]
`it returns an exception with the top-5 nearest words. Is there an instance where I can extract this top-5 nearest words returned so that I can use those word vectors?`.

Sure, can do it. Will bump it in next version.

Steps to pretrain the models, https://github.com/huseinzol05/Malaya/tree/master/pretrained-model/wordvector
